-- MySQL Script generated by MySQL Workbench
-- Tue Sep 12 09:34:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema 2017-mn-group-09
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `2017-mn-group-09` ;

-- -----------------------------------------------------
-- Schema 2017-mn-group-09
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2017-mn-group-09` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema 2017-mn-group-09-test
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `2017-mn-group-09-test` ;

-- -----------------------------------------------------
-- Schema 2017-mn-group-09-test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2017-mn-group-09-test` DEFAULT CHARACTER SET utf8 ;
USE `2017-mn-group-09` ;

-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`account_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`account_names` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `creation_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`accounts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` DATE NOT NULL,
  `value` DOUBLE NOT NULL,
  `companies_id` INT(11) NOT NULL,
  `account_names_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `companies_id`, `account_names_id`),
  INDEX `fk_accounts_companies_idx` (`companies_id` ASC),
  INDEX `fk_accounts_account_names_idx` (`account_names_id` ASC),
  CONSTRAINT `fk_accounts_account_names1`
    FOREIGN KEY (`account_names_id`)
    REFERENCES `2017-mn-group-09`.`account_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounts_companies`
    FOREIGN KEY (`companies_id`)
    REFERENCES `2017-mn-group-09`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`indicators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`indicators` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `expression` VARCHAR(100) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_indicators_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_indicators_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `2017-mn-group-09`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`methodology_comparators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`methodology_comparators` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dtype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`methodologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`methodologies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `indicators_id` INT(11) NOT NULL,
  `methodology_comparators_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_methodologies_indicators_idx` (`indicators_id` ASC),
  INDEX `fk_methodologies_methodology_comparators_idx` (`methodology_comparators_id` ASC),
  INDEX `fk_methodologies_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_methodologies_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `2017-mn-group-09`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_methodologies_indicators`
    FOREIGN KEY (`indicators_id`)
    REFERENCES `2017-mn-group-09`.`indicators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_methodologies_methodology_comparators`
    FOREIGN KEY (`methodology_comparators_id`)
    REFERENCES `2017-mn-group-09`.`methodology_comparators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`methodology_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`methodology_companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `methodologies_id` INT(11) NOT NULL,
  `companies_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_companies_methodologies_idx` (`methodologies_id` ASC),
  INDEX `fk_methodology_companies_companies_idx` (`companies_id` ASC),
  CONSTRAINT `fk_methodology_companies_methodologies`
    FOREIGN KEY (`companies_id`)
    REFERENCES `2017-mn-group-09`.`companies` (`id`),
  CONSTRAINT `fk_methodology_companies_companies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`methodology_own`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`methodology_own` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `methodologies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_own_methodologies_idx` (`methodologies_id` ASC),
  CONSTRAINT `fk_methodology_own_methodologies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09`.`methodology_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09`.`methodology_values` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` DOUBLE NULL DEFAULT NULL,
  `methodologies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_values_methodologies_idx` (`methodologies_id` ASC),
  CONSTRAINT `fk_methodology_values_methodologies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

insert into users(username,password)
values("test","test");

insert into users(username,password)
values("test2","test2");

USE `2017-mn-group-09-test` ;

-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`account_names`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`account_names` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `creation_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`accounts` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `timestamp` DATE NOT NULL,
  `value` DOUBLE NOT NULL,
  `companies_id` INT(11) NOT NULL,
  `account_names_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `companies_id`, `account_names_id`),
  INDEX `fk_accounts_companies_idx` (`companies_id` ASC),
  INDEX `fk_accounts_account_names_idx` (`account_names_id` ASC),
  CONSTRAINT `fk_accounts_account_names1`
    FOREIGN KEY (`account_names_id`)
    REFERENCES `2017-mn-group-09-test`.`account_names` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accounts_companies`
    FOREIGN KEY (`companies_id`)
    REFERENCES `2017-mn-group-09-test`.`companies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`indicators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`indicators` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `expression` VARCHAR(100) NULL DEFAULT NULL,
  `users_id` INT(11) NOT NULL,  
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `fk_indicators_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_indicators_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `2017-mn-group-09-test`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`methodology_comparators`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`methodology_comparators` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `dtype` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`methodologies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`methodologies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `indicators_id` INT(11) NOT NULL,
  `methodology_comparators_id` INT(11) NOT NULL,
  `users_id` INT(11) NOT NULL,  
  PRIMARY KEY (`id`),
  INDEX `fk_methodologies_indicators_idx` (`indicators_id` ASC),
  INDEX `fk_methodologies_methodology_comparators_idx` (`methodology_comparators_id` ASC),
  INDEX `fk_methodologies_users_idx` (`users_id` ASC),
  CONSTRAINT `fk_methodologies_users`
    FOREIGN KEY (`users_id`)
    REFERENCES `2017-mn-group-09-test`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_methodologies_indicators`
    FOREIGN KEY (`indicators_id`)
    REFERENCES `2017-mn-group-09-test`.`indicators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_methodologies_methodology_comparators`
    FOREIGN KEY (`methodology_comparators_id`)
    REFERENCES `2017-mn-group-09-test`.`methodology_comparators` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`methodology_companies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`methodology_companies` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `methodologies_id` INT(11) NOT NULL,
  `companies_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_companies_methodologies_idx` (`methodologies_id` ASC),
  INDEX `fk_methodology_companies_companies_idx` (`companies_id` ASC),
  CONSTRAINT `fk_methodology_companies_methodologies`
    FOREIGN KEY (`companies_id`)
    REFERENCES `2017-mn-group-09-test`.`companies` (`id`),
  CONSTRAINT `fk_methodology_companies_companies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09-test`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;



-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`methodology_own`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`methodology_own` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `methodologies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_own_methodologies_idx` (`methodologies_id` ASC),
  CONSTRAINT `fk_methodology_own_methodologies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09-test`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `2017-mn-group-09-test`.`methodology_values`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017-mn-group-09-test`.`methodology_values` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `value` DOUBLE NULL DEFAULT NULL,
  `methodologies_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `methodologies_id`),
  INDEX `fk_methodology_values_methodologies_idx` (`methodologies_id` ASC),
  CONSTRAINT `fk_methodology_values_methodologies`
    FOREIGN KEY (`methodologies_id`)
    REFERENCES `2017-mn-group-09-test`.`methodologies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


DROP USER if exists 'user_app';

CREATE USER 'user_app' IDENTIFIED BY '1234';

GRANT ALL ON `2017-mn-group-09`.* TO 'user_app';

DROP USER if exists 'user_test' ;

CREATE USER 'user_test' IDENTIFIED BY '1234';

GRANT ALL ON `2017-mn-group-09-test`.* TO 'user_test';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
